name: Build Codesigned Starship Binary
on: push

# Artifact names: 
#  - starship-x86_64-apple-darwin.tar.gz
#  - starship-aarch64-apple-darwin.tar.gz

jobs:
  build-dummy:
    name: Dummy Build Protocol
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macOS-11
            name: starship-x86_64-apple-darwin.tar.gz

          - target: aarch64-apple-darwin
            os: macOS-11
            name: starship-aarch64-apple-darwin.tar.gz

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}
      - name: Build | Build
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --locked --target ${{ matrix.target }}
      - name: Post Build | Prepare artifacts [-nix]
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip starship || true
          tar czvf ../../../${{ matrix.name }} starship
          cd -
      - name: Deploy | Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}


  sign-and-notarize:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            arch: x86_64
            os: macOS-11
            name: starship-x86_64-apple-darwin.tar.gz
            pkgname: starship-x86_64.pkg

          - target: aarch64-apple-darwin
            arch: aarch64
            os: macOS-11
            name: starship-aarch64-apple-darwin.tar.gz
            pkgname: starship-aarch64.pkg

    env:
      KEYCHAIN_FILENAME: app-signing.keychain-db
      KEYCHAIN_ENTRY: AC_PASSWORD
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up certificates and keychains
      env:
        APP_CERTIFICATE_BASE64: ${{ secrets.APPLEDEV_APPSIGNKEY_BASE64 }}
        INSTALL_CERTIFICATE_BASE64: ${{ secrets.APPLEDEV_INSTALLERSIGNKEY_BASE64 }}
        P12_PASSWORD: ${{ secrets.APPLEDEV_SIGNKEY_PASS }}
        KEYCHAIN_PASSWORD: ${{ secrets.APPLEDEV_SIGNKEY_PASS }}
        APPLEID_USERNAME: ${{ secrets.APPLEDEV_ID_NAME }}
        APPLEID_TEAMID: ${{ secrets.APPLEDEV_TEAM_ID }}
        APPLEID_PASSWORD: ${{ secrets.APPLEDEV_PASSWORD }}
      run: |
        APP_CERTIFICATE_PATH="$RUNNER_TEMP/app_certificate.p12"
        INSTALL_CERTIFICATE_PATH="$RUNNER_TEMP/install_certificate.p12"
        KEYCHAIN_PATH="$RUNNER_TEMP/$KEYCHAIN_FILENAME"

        # import certificate and provisioning profile from secrets
        echo -n "$APP_CERTIFICATE_BASE64" | base64 --decode --output $APP_CERTIFICATE_PATH
        echo -n "$INSTALL_CERTIFICATE_BASE64" | base64 --decode --output $INSTALL_CERTIFICATE_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
        security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

        # import certificate to keychain
        security import $APP_CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security import $INSTALL_CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # Add Apple Developer ID credentials to keychain
        xcrun notarytool store-credentials "$KEYCHAIN_ENTRY" --team-id "$APPLEID_TEAMID" --apple-id "$APPLEID_USERNAME" --password "$APPLEID_PASSWORD" --keychain "$KEYCHAIN_PATH"

    - name: Notarize | Build docs
      run: |
        cd docs
        npm install
        npm run build

    - name: Notarize | Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.name }}

    - name: What's here?
      run: ls -al

    - name: Build/Sign/Notarize Flat Package
      run: |
        tar xf ${{ matrix.name }}
        bash install/macos_packages/build_and_notarize.sh starship docs ${{ matrix.arch }} ${{  matrix.pkgname }}

    - name: Upload Notarized Starship ZIP
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.pkgname }}
        path: ${{ matrix.pkgname }}
        retention-days: 1

    - name: Cleanup Secrets
      if: ${{ always() }}
      run: |
        KEYCHAIN_PATH="$RUNNER_TEMP/$KEYCHAIN_FILENAME"
        security delete-keychain $KEYCHAIN_PATH